"""Tabelas Iniciais

Revision ID: 8997790b1a46
Revises: 
Create Date: 2023-02-12 14:05:47.470296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8997790b1a46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('logradouro', sa.String(length=250), nullable=True),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('matriz', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_id'), 'empresa', ['id'], unique=False)
    op.create_table('pessoa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoa_id'), 'pessoa', ['id'], unique=False)
    op.create_table('departamento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('local', sa.String(length=200), nullable=False),
    sa.Column('id_empresa', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departamento_id'), 'departamento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departamento_id'), table_name='departamento')
    op.drop_table('departamento')
    op.drop_index(op.f('ix_pessoa_id'), table_name='pessoa')
    op.drop_table('pessoa')
    op.drop_index(op.f('ix_empresa_id'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
