"""Estrtutura inicial

Revision ID: 9cc0564d755d
Revises:
Create Date: 2023-04-02 14:19:33.777120

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "9cc0564d755d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "empresa",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
        sa.Column(
            "logradouro", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True
        ),
        sa.Column(
            "cidade", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True
        ),
        sa.Column("estado", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("matriz", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_empresa_id"), "empresa", ["id"], unique=False)
    op.create_table(
        "pessoa",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
        sa.Column(
            "telefone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pessoa_id"), "pessoa", ["id"], unique=False)
    op.create_table(
        "departamento",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column(
            "local", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("id_empresa", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_empresa"],
            ["empresa.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departamento_id"), "departamento", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_departamento_id"), table_name="departamento")
    op.drop_table("departamento")
    op.drop_index(op.f("ix_pessoa_id"), table_name="pessoa")
    op.drop_table("pessoa")
    op.drop_index(op.f("ix_empresa_id"), table_name="empresa")
    op.drop_table("empresa")
    # ### end Alembic commands ###
